CarService/Models/IndividualButtonPartial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarService.Models
{
    public class IndividualButtonPartial
    {
        public string ButtonType { get; set; }
        public string Action { get; set; }
        public string Glyphicon { get; set; }
        public string Text { get; set; }

        public int? ServiceId { get; set; }
        public string CustomerId { get; set; }
        public int? CarId { get; set; }

        public string ActionParameters
        {
            get
            {
                var param = new StringBuilder(@"/");
                if(ServiceId != 0 && ServiceId != null)
                {
                    param.Append(String.Format("{0}", ServiceId));
                }
                if (CustomerId != null && CustomerId.Length > 0)
                {
                    param.Append(String.Format("{0}", CustomerId));
                }
                if (CarId != 0 && CarId != null)
                {
                    param.Append(String.Format("{0}", CarId));
                }

                return param.ToString().Substring(0, param.Length);
            }
        }
    }
}

CarService/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarService.Data;
using CarService.Models;
using CarService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarService.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CarsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string userId = null)
        {

            if(userId == null)
            {
                //Only called when a customer user logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel
            {
                Cars = _db.Cars.Where(c => c.UserId == userId),
                UserObj = _db.Users.FirstOrDefault(u => u.Id == userId)
            };

            return View(model);
        }

        //Create GET
        public IActionResult Create(string userId)
        {
            Car carObj = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };
            return View(carObj);
        }

        //Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId });
            }

            return View(car);
        }

        //Details GET
        public async Task<IActionResult> Details (int? id)
        {
            if(id== null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if(car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //EDIT GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //EDIT POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if(id!= car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId });
            }

            return View(car);
        }

        //DELETE GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //Delete POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _db.Cars.SingleOrDefaultAsync(c => c.Id == id);
            if (car == null)
            {
                return NotFound();
            }
            _db.Cars.Remove(car);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { userId = car.UserId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

CarService/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarService.Data;
using CarService.Models;
using CarService.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarService.Controllers
{
    [Authorize(Roles =SD.AdminEndUser)]
    public class ServiceTypesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ServiceTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET : ServiceType
        public IActionResult Index()
        {
            return View(_db.ServiceType.ToList());
        }

        //GET: ServiceType/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
                _db.Add(serviceType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }

        //Details : ServiceTypes/Details/1
        public async Task<IActionResult> Details (int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var serviceType = await _db.ServiceType.SingleOrDefaultAsync(m => m.Id == id);
            if(serviceType == null)
            {
                return NotFound();
            }
            return View(serviceType);
        }

        //Edit : ServiceTypes/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var serviceType = await _db.ServiceType.SingleOrDefaultAsync(m => m.Id == id);
            if (serviceType == null)
            {
                return NotFound();
            }
            return View(serviceType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ServiceType serviceType)
        {
            if(id != serviceType.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Update(serviceType);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }

            //Delete : ServiceTypes/Delete/1
            public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var serviceType = await _db.ServiceType.SingleOrDefaultAsync(m => m.Id == id);
            if (serviceType == null)
            {
                return NotFound();
            }
            return View(serviceType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveServiceType(int id)
        {
            var serviceType = await _db.ServiceType.SingleOrDefaultAsync(m => m.Id == id);
            _db.ServiceType.Remove(serviceType);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

CarService/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarService.Data;
using CarService.Models;
using CarService.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarService.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class UsersController : Controller
    {

        private ApplicationDbContext _db;

        public UsersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string option=null, string search=null)
        {
            var users = _db.Users.ToList();

            if (option == "email" && search != null)
            {
                users = _db.Users.Where(u => u.Email.ToLower().Contains(search.ToLower())).ToList();
            }
            else
            {
                if (option == "name" && search != null)
                {
                    users = _db.Users.Where(u => u.FirstName.ToLower().Contains(search.ToLower())
                    || u.LastName.ToLower().Contains(search.ToLower())).ToList();
                }
                else
                {
                    if (option == "phone" && search != null)
                    {
                        users = _db.Users.Where(u => u.PhoneNumber.ToLower().Contains(search.ToLower())).ToList();
                    }
                }
            }

            return View(users);
        }

        // GET Details
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // GET Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        //POST Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (ApplicationUser user)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", user);
            }
            else
            {
                var userInDb = await _db.Users.SingleOrDefaultAsync(u => u.Id == user.Id);
                if(userInDb == null)
                {
                    return NotFound();
                }
                else
                {
                    userInDb.FirstName = user.FirstName;
                    userInDb.LastName = user.LastName;
                    userInDb.PhoneNumber = user.PhoneNumber;
                    userInDb.Address = user.Address;
                    userInDb.City = user.City;
                    userInDb.PostalCode = user.PostalCode;

                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

            }
        }

        // GET Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userInDb = await _db.Users.SingleOrDefaultAsync(u => u.Id == id);

            var cars = _db.Cars.Where(x => x.UserId == userInDb.Id);

            List<Car> listCar = cars.ToList();

            foreach( var car in listCar)
            {
                var services = _db.Services.Where(x => x.CarId == car.Id);

                _db.Services.RemoveRange(services);
            }

            _db.Cars.RemoveRange(cars);
            _db.Users.Remove(userInDb);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

CarService/Views/Shared/_CarDetailsInService.cshtml
@model CarService.ViewModel.CarAndServiceViewModel

<h4>Car record for Customer</h4>
<div class="row form-border">
    <div class="col-sm-5">
        @*Make and Model*@
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Make" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px">
                <input asp-for="Make" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Model" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px">
                <input asp-for="Model" disabled class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        @* Style and Year*@
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Style" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px">
                <input asp-for="Style" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Year" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px">
                <input asp-for="Year" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>

CarService/Views/Shared/_DisplayPastServices.cshtml
@model CarService.ViewModel.CarAndServiceViewModel
@using CarService.Utility

<div>
    <table class="table table-condensed table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.PastServicesObj.FirstOrDefault().Miles)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServicesObj.FirstOrDefault().Price)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServicesObj.FirstOrDefault().Details)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServicesObj.FirstOrDefault().DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.PastServicesObj.FirstOrDefault().ServiceType.Name)
            </th>
            <th></th>
        </tr>
        @foreach(var item in Model.PastServicesObj)
        {
        <tr>
            <td>
                @Html.DisplayFor(m => item.Miles)
            </td>
            <td>
                @Html.DisplayFor(m => item.Price)
            </td>
            <td>
                @Html.DisplayFor(m => item.Details)
            </td>
            <td>
                @Html.DisplayFor(m => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(m => item.ServiceType.Name)
            </td>
            <td>
                @if(item.DateAdded.Date == DateTime.Now.Date && User.IsInRole(SD.AdminEndUser))
                {
                    @Html.Partial("_IndividualButtonPartial",
                    new IndividualButtonPartial
                    {
                        Action="Delete",
                        ButtonType="btn-danger",
                        Glyphicon="trash",
                        Text="Delete Button",
                        ServiceId=item.Id

                    })

                }
            </td>
        </tr>

        }
    </table>
</div>

CarService/Views/Shared/_IndividualButtonPartial.cshtml
@model CarService.Models.IndividualButtonPartial

<a type="button" class="btn btn-sm @Model.ButtonType"
   href="@Url.Action(Model.Action)@Model.ActionParameters">
    <span class="glyphicon glyphicon-@Model.Glyphicon">
    </span>
    <span class="sr-only">@Model.Text</span>
</a>

CarService/Views/Shared/_Layout.cshtml
@using CarService.Utility

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarService</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CarService</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(SD.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    }
                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Cars</a></li>
                    @if (User.IsInRole(SD.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="ServiceTypes" asp-action="Index">Service Types</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">&copy; 2018 - CarService</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CarService/Views/Shared/_TableButtonPartial.cshtml
@model CarService.Models.IndividualButtonPartial

<td style="width:150px;">
    <div class="btn-group" role="group">
        @Html.Partial("_IndividualButtonPartial",
          new IndividualButtonPartial
          {
              Action = "Edit",
              ButtonType = "btn-primary",
              Glyphicon = "pencil",
              Text = "Edit Button",
              ServiceId = Model.ServiceId,
              CustomerId = Model.CustomerId,
              CarId=Model.CarId
          })

        @Html.Partial("_IndividualButtonPartial",
          new IndividualButtonPartial
          {
              Action = "Details",
              ButtonType = "btn-success",
              Glyphicon = "list",
              Text = "Details Button",
              ServiceId = Model.ServiceId,
              CustomerId = Model.CustomerId,
              CarId = Model.CarId
          })

        @Html.Partial("_IndividualButtonPartial",
         new IndividualButtonPartial
         {
             Action = "Delete",
             ButtonType = "btn-danger",
             Glyphicon = "trash",
             Text = "Delete Button",
             ServiceId = Model.ServiceId,
             CustomerId = Model.CustomerId,
             CarId = Model.CarId
         })
    </div>
</td>