CarService/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarService.Models
{
    public class Car
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string VIN { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        public string Style { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public double Miles { get; set; }
        public string Color { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

CarService/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarService.Data;
using CarService.Models;
using CarService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarService.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CarsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string userId = null)
        {

            if(userId == null)
            {
                //Only called when a customer user logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel
            {
                Cars = _db.Cars.Where(c => c.UserId == userId),
                UserObj = _db.Users.FirstOrDefault(u => u.Id == userId)
            };

            return View(model);
        }

        //Create GET
        public IActionResult Create(string userId)
        {
            Car carObj = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };
            return View(carObj);
        }

        //Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId });
            }

            return View(car);
        }

        //Details GET
        public async Task<IActionResult> Details (int? id)
        {
            if(id== null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if(car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //EDIT GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //EDIT POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if(id!= car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = car.UserId });
            }

            return View(car);
        }

        //DELETE GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (car == null)
            {
                NotFound();
            }

            return View(car);
        }

        //Delete POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _db.Cars.SingleOrDefaultAsync(c => c.Id == id);
            if (car == null)
            {
                return NotFound();
            }
            _db.Cars.Remove(car);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { userId = car.UserId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

CarService/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarService.Data;
using CarService.Models;
using CarService.Utility;
using CarService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarService.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ServicesController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Authorize]
        public IActionResult Index(int carId)
        {
            var car = _db.Cars.FirstOrDefault(c => c.Id == carId);
            var model = new CarAndServiceViewModel
            {
                carId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                VIN = car.VIN,
                Year = car.Year,
                UserId = car.UserId,
                ServiceTypesObj = _db.ServiceType.ToList(),
                PastServicesObj = _db.Services.Where(s => s.CarId == carId).OrderByDescending(s => s.DateAdded)
            };

            return View(model);
        }

        [Authorize(Roles = SD.AdminEndUser)]
        //GET : Services/Create
        public IActionResult Create(int carId)
        {
            var car = _db.Cars.FirstOrDefault(c => c.Id == carId);
            var model = new CarAndServiceViewModel
            {
                carId=car.Id,
                Make=car.Make,
                Model=car.Model,
                Style=car.Style,
                VIN=car.VIN,
                Year=car.Year,
                UserId=car.UserId,
                ServiceTypesObj = _db.ServiceType.ToList(),
                PastServicesObj = _db.Services.Where(s => s.CarId == carId).OrderByDescending(s => s.DateAdded).Take(5)
            };

            return View(model);
        }

        [Authorize(Roles = SD.AdminEndUser)]
        //POST : Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarAndServiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.NewServiceObj.CarId = model.carId;
                model.NewServiceObj.DateAdded = DateTime.Now;
                _db.Add(model.NewServiceObj);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Create), new { carId = model.carId });
            }

            var car = _db.Cars.FirstOrDefault(c => c.Id == model.carId);
            var newModel = new CarAndServiceViewModel
            {
                carId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                VIN = car.VIN,
                Year = car.Year,
                UserId=car.UserId,
                ServiceTypesObj = _db.ServiceType.ToList(),
                PastServicesObj = _db.Services.Where(s => s.CarId == model.carId).OrderByDescending(s => s.DateAdded).Take(5)
            };

            return View(newModel);

        }

        [Authorize(Roles = SD.AdminEndUser)]
        //DELETE GET
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var service = await _db.Services.Include(s => s.Car).Include(s => s.ServiceType)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        [Authorize(Roles = SD.AdminEndUser)]
        //POST Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Service model){
            var serviceId = model.Id;
            var carId = model.CarId;
            var service = await _db.Services.SingleOrDefaultAsync(m => m.Id == serviceId);
            if(service == null)
            {
                return NotFound();
            }

            _db.Services.Remove(service);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Create), new { carId = carId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

CarService/Views/Cars/Create.cshtml
@model CarService.Models.Car
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Add New Car</h2>
<hr />

<form asp-action="Create">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="VIN" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="VIN" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="VIN" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Make" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Make" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Model" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Model" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Style" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Style" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Style" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Year" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Year" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Year" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Miles" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Miles" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Miles" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Color" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Color" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Color" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Add Car" class="btn btn-sm btn-primary" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
    <input asp-for="UserId" type="hidden" />
</form>

CarService/Views/Cars/Delete.cshtml
@model CarService.Models.Car
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2>Delete Car</h2>
<hr />

<form asp-action="Delete">
    <div class="form-border">
        <fieldset disabled>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="VIN" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="VIN" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Make" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Make" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Model" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Model" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Style" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Style" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Year" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Year" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Miles" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Miles" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Color" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Color" class="form-control" />
                    </div>
                </div>
            </div>
        </fieldset>
        <br />
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
</form>

CarService/Views/Cars/Details.cshtml
@model CarService.Models.Car
@{
    ViewData["Title"] = "Details";
}

<br />
<h2>Car Details</h2>
<hr />


    <div class="form-border">
        <fieldset disabled>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="VIN" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="VIN" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Make" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Make" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Model" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Model" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Style" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Style" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Year" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Year" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Miles" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Miles" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Color" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Color" class="form-control" />
                    </div>
                </div>
            </div>
            <br />
        </fieldset>
            <div class="form-group">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-primary">Edit</a>
                <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to List</a>
            </div>
    </div>

CarService/Views/Cars/Edit.cshtml
@model CarService.Models.Car
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Edit Car</h2>
<hr />

<form asp-action="Edit">
    <div class="form-border">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="UserId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="VIN" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="VIN" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="VIN" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Make" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Make" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Model" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Model" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Style" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Style" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Style" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Year" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Year" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Year" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Miles" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Miles" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Miles" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Color" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Color" class="form-control" />
                </div>
            </div>
            <span asp-validation-for="Color" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-sm btn-primary" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
</form>

CarService/Views/Cars/Index.cshtml
@model CarService.ViewModel.CarAndCustomerViewModel
@using CarService.Utility
@{
    ViewData["Title"] = "Index";
}

<br />
<h2>Car Record for Customer</h2>
<div class="row" style="padding-bottom:80px">
    <div class="col-sm-6" style="padding-bottom:80px">
        @* Add Create New car Button *@
        <a asp-action="Create" asp-route-userId="UserObj.Id" class="btn btn-primary" style="width:150px;">Add New Car</a>
    </div>
    <div class="col-sm-6">
        @* Display User Details*@
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.FirstName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px">
                <input asp-for="UserObj.FirstName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.LastName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px">
                <input asp-for="UserObj.LastName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.PhoneNumber" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px">
                <input asp-for="UserObj.PhoneNumber" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.Email" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px">
                <input asp-for="UserObj.Email" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>
@if(Model.Cars.Count() == 0)
{
    <div class="text-primary form-border"> No Car Found! Please add a car...</div>

}
else
{
    <div class="form-border">
        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().VIN)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Make)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Model)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Style)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Color)
                </th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model.Cars)
            {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.VIN)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Make)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Style)
                </td>
                <td>
                    @Html.DisplayFor(m => item.Color)
                </td>
                @if (User.IsInRole(SD.CustomerEndUser))
                {
                    <td style="width:100px">
                        <a class="btn btn-primary btn-sm" asp-controller="Services" asp-action="Index" asp-route-carId="@item.Id">
                            <span class="glyphicon glyphicon-wrench"></span>&nbsp; Service History
                        </a>
                    </td>
                }
                else
                {
                    <td style="width:100px">
                        <a class="btn btn-success btn-sm" asp-controller="Services" asp-action="Create" asp-route-carId="@item.Id">
                            <span class="glyphicon glyphicon-plus-sign"></span>&nbsp; New Service
                        </a>
                    </td>
                }
                <td>
                    @Html.Partial("_TableButtonPartial", new IndividualButtonPartial { CarId=item.Id})
                </td>
            </tr>

            }
        </table>
    </div>

}